### ISSUE TITLE
Fix PathValidationError

### ISSUE THREAD

**Issue by bennyn** [wireapp/wire-web-packages#714]
```
Uncaught rejection "PathValidationError" (undefined): Path traversal has been detected on "amplify\z.storage.StorageKey.EVENT.LAST_DATE". { Error
    at new PathValidationError (D:\dev\projects\wireapp\wire-web-packages\packages\store-engine\dist\commonjs\engine\error\PathValidationError.js:21:23)
    at D:\dev\projects\wireapp\wire-web-packages\packages\store-engine\dist\commonjs\engine\FileEngine.js:108:31
    at new Promise (<anonymous>)
    at FileEngine.resolvePath (D:\dev\projects\wireapp\wire-web-packages\packages\store-engine\dist\commonjs\engine\FileEngine.js:105:16)
    at FileEngine.read (D:\dev\projects\wireapp\wire-web-packages\packages\store-engine\dist\commonjs\engine\FileEngine.js:178:21)
    at NotificationDatabaseRepository.getLastEventDate (D:\dev\projects\wireapp\wire-web-packages\packages\core\dist\notification\NotificationDatabaseRepository.js:22:14)
    at NotificationService.setLastEventDate (D:\dev\projects\wireapp\wire-web-packages\packages\core\dist\notification\NotificationService.js:37:14)
    at NotificationService.initializeNotificationStream (D:\dev\projects\wireapp\wire-web-packages\packages\core\dist\notification\NotificationService.js:21:21)
    at D:\dev\projects\wireapp\wire-web-packages\packages\core\dist\Account.js:196:47
    at <anonymous> name: 'PathValidationError' }
```

**Comment by bennyn** [comment]
#done
